# fly.toml app configuration file generated for mi-sunat
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mi-sunat'
primary_region = 'mia'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'n8n_data'
  destination = '/home/node/.n8n'

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
